### ISSUE TITLE
Properties Inaccessible when device is removed.

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher#4]
### Details:
Audio Switcher
Version: 1.6.3.1
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
unplugged a device i think
### Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.get_FullName()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshNotifyIconItems()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshPlaybackDevices()
```

**Comment by xenolightning** [comment]
Fixed with the new CachedPropertyStore.

**Comment by xenolightning** [comment]
#7 should also address this one.
